### PR TITLE
Add backtrace_path_filter config option

### PR DESCRIPTION
**Pull request by jeremycw**
## What

Adds a config option called `backtrace_path_filter` that allows the lines in backtraces to be compared against the filter to see if they should be included in the backtrace

## Why

Backtraces are limited to a number of lines (default 30) and are often coming from so deep in library/framework code that you may not even see the originating user code in the backtrace. However, library code is often located in a different path than user code. This can be leveraged to filter the call stack to relevant code.

```ruby
[
  '/usr/local/bundle/rails/...',
  '/usr/local/bundle/rails/...',
  '/usr/local/bundle/rails/...',
  '/usr/local/bundle/rails/...',
  '/usr/local/bundle/rails/...',
  '/usr/local/bundle/rails/...',
  '/usr/local/bundle/rails/...',
  '/usr/local/bundle/rails/...',
  '/usr/local/bundle/rails/...',
  # potentially many more lines...
  '/var/www/app/my/model.rb',
  '/var/www/app/my/controller.rb',
  '/usr/local/bundle/rails/...',
  '/usr/local/bundle/rails/...'
]

# With `backtrace_path_filter` set to `/var/www/app/` becomes:

[
  '/var/www/app/my/model.rb',
  '/var/www/app/my/controller.rb'
]
```

### CODE REVIEW

**Comment by hmadison** [comment]
Hey @jeremycw,

Since this seems to be a Rails related pull request, would it be possible to make the configuration option take a lambda instead of a string so users could pass closures to `ActiveSupport::BacktraceCleaner`? I would also ask that we add tests for this behavior. For core functionality we would like to keep our 100% branch coverage. 

Thanks,
Hunter

**Comment by jeremycw** [comment]
@hmadison Good suggestion. I confirmed that it also works doing `->(trace) { Rails.backtrace_cleaner.clean(trace) }`

**Comment by daande** [comment]
@hmadison we created a support request in instana (https://support.instana.com/hc/en-us/requests/25636) hopefully that is sufficient

**Comment by daande** [comment]
@hmadison any update on this? See attached ticket above.

**Comment by hmadison** [comment]
I've merged the change and will work on getting a new release pushed tomorrow morning.

**Comment by daande** [comment]
@hmadison can you cut a release with this change please?

**Comment by hmadison** [comment]
@daande https://rubygems.org/gems/instana/versions/1.209.1

**Pull request merged**
