### PR TITLE
Implement Sidekiq instrumentation

### PR DESCRIPTION
**Pull request by nguyenquangminh0711**
Hi @pglombardo, it's me again. I completed the Sidekiq instrumentation based on your recommendation. I tested on my staging system and everything seems to work, just wait for the support of Instana back-end for better UI. 

screen shot 2017-07-17 at 16 39 46

screen shot 2017-07-17 at 17 01 01

This pull request has some differences in the test suite configuration comparing to your previous implementation. I'm not sure about the cleanness of my configuration, but I don't have better solution for it. Please have a look and give me some feedbacks 💃 

Oh and one more thing, should we track the arguments of the Job? That would be helpful for the tracing but not sure about the size of the span. If arguments are complicated object, it would be a big mess.

- [x] Sidekiq client middleware instrumentation & tests
- [x] Sidekiq worker middleware instrumentation & tests
- [x] Add Sidekiq to libraries gemfile
- [x] Add/configure sidekiq worker into test suite
- [x] Pass and pickup context from client enqueue side to job
- [ ] Add backend support for sidekiq span types
- [ ] Add UI support for sidekiq spans

### CODE REVIEW

**Comment by pglombardo** [comment]
Yay @nguyenquangminh0711 - great stuff!  I'll go through this shortly, test locally and see what's needed to add backend support.

**Comment by pglombardo** [comment]
Hi @nguyenquangminh0711 Everything looks great.

I'm adding backend and UI support today.  I hope to merge this sometime between today and this weekend and release early next week.  Sorry for the delay.  I've been juggling a few tasks this week. 
 FYI

**Comment by pglombardo** [comment]
Works great.  Going to merge and create a separate PR to finish up UI and backend support.  Thanks @nguyenquangminh0711

**Comment by nguyenquangminh0711** [comment]
Hi @pglombardo, is everything okay with the sidekiq instrumentation implementation? Have you schedule to release it yet? Look forward to the release so that my company could use an officially version 💃

**Comment by pglombardo** [comment]
Hi @nguyenquangminh0711 - We were just talking about this now.  I'm going to release a gem today and UI and backend support will be released early next week (likely Monday I believe).  Sorry for the delay - juggling a few too many things the last couple weeks.  ;-)

**Comment by pglombardo** [comment]
Correction: UI/Backend release is likely tomorrow if we don't find any blockers.

**Pull request merged**
