### PR TITLE
Redis instrumentation

### PR DESCRIPTION
**Pull request by nguyenquangminh0711**
Hi @pglombardo, this is the pull implementing the Redis instrumentation. Although I almost finished it, I'm really confused whether we should add this instrumentation into standard sensor or just let the users handle it by themselves. At my company, we have complicated Redis usage, so the instrumentation is essential. However, I'm not sure about other people's usage. So, in case you consider this instrumentation does not belong to standard sensor, please let me know and just close this pull. I'll move this into a plugin for my company 😃 

screen shot 2017-08-09 at 01 58 01

- [x] Normal call instrumentation
- [x] Pipleline support
- [x] Multi support
- [x] Instana back-end and UI support

### CODE REVIEW

**Comment by pglombardo** [comment]
Hi @nguyenquangminh0711 you're on a roll 😉 

> Different drivers support (such as hiredis)?

If we're going to do this, let's make it separate instrumentation/PR since the hooks will likely be different.  So let's leave out hiredis for this PR.

As @CodingFabian said, the two minimally required fields for _already existing_ backend/UI redis support is:

```ruby
kv_payload[:redis][:command] = :set
kv_payload[:redis][:connection] = "localhost:6379"
```

So you'll have to flip your reporting of `command` and `operation`.  This is because other languages already use this backend/UI API that we already have in place.

And the last thing, if you add `:redis` to this list of [REGISTERED_SPANS](https://github.com/instana/ruby-sensor/blob/master/lib/instana/tracing/span.rb#L3) and [EXIT_SPANS](https://github.com/instana/ruby-sensor/blob/master/lib/instana/tracing/span.rb#L7), this should work out of the box.

**Comment by nguyenquangminh0711** [comment]
@CodingFabian @pglombardo Hi, I updated the pull request to slim down the captured information and adds Redis to Registered span and Exit spans. Everything works great on front-end too 👍 

screen shot 2017-08-11 at 11 04 47

**Comment by CodingFabian** [comment]
very cool, good job!
@pglombardo will take care of merging and releasing.

**Comment by pglombardo** [comment]
Great stuff @nguyenquangminh0711.  I'm going to merge, build/deploy/test an RC gem and look to release today.  Thanks again!

**Pull request merged**
