### PR TITLE
Sidekiq Instrumentation

### PR DESCRIPTION
**Pull request by pglombardo**
This PR adds visibility into Sidekiq queueing and job processing.

- [ ] Sidekiq client middleware instrumentation & tests
- [ ] Sidekiq worker middleware instrumentation & tests
- [x] Add Sidekiq to libraries gemfile
- [ ] Add/configure sidekiq worker into test suite
- [ ] Pass and pickup context from client enqueue side to job
- [ ] Add backend support for sidekiq span types
- [ ] Add UI support for sidekiq spans

### CODE REVIEW

**Comment by nguyenquangminh0711** [comment]
Hi @pglombardo, this pull is hang for months. What's wrong with this pull? Could I help so that we could release this soon? 👍

**Comment by pglombardo** [comment]
Hi @nguyenquangminh0711 by all means.  That would be a great help.  Thus far, this has been put on hold simply because I've been juggling with other tasks.

I'll update this branch and add a task list.  I think the major parts missing are worker instrumentation and the tests.

**Comment by nguyenquangminh0711** [comment]
@pglombardo Hi Pete, I'm working on Sidekiq instrumentation. I got a problem with Ruby version. The latest version of Sidekiq (5.0.3) does not support Ruby versions below 2.2.2. What do you think about the solution for this issue? Should we should drop the support of instana for Ruby under 2.2.2 for sidekiq? Or Should we enforce a lower version of sidekiq when using Ruby under 2.2.2?

**Comment by pglombardo** [comment]
Hrm good question.  

Is the instrumentation the same for latest Sidekiq and legacy Sidekiq?

If they are the same, I would just wrap instrumentation and tests in an if block:

```ruby
if defined?(::Sidekiq) && 
    ((Sidekiq::VERSION::Major == 5 && RUBY_VERSION >= '2.2.2') || Sidekiq::Version::Major < 5)
  # This block should execute:
  #   - always for Sidekiq versions v4 and earlier
  #   - if Sidekiq version is 5 and Ruby version is 2.2.2 or newer
  
  # ...
  # instrumentation and/or tests
  # ...
end
```

If the instrumentation varies for older versions, we could always add `lib/instana/instrumentation/sidekiq_legacy.rb` later on to support older versions.

```ruby
if defined?(::Sidekiq) &&  Sidekiq::Version::Major < 5
  # legacy sidekiq instrumentation/tests
end
```

**Comment by pglombardo** [comment]
Graciously implemented by @nguyenquangminh0711 in #82.  Closing this PR.

**Pull request closed without merging**
